### ISSUE TITLE
revert seamless switch to local storage

### ISSUE THREAD

**Issue by anonymousblackterminal** [Cosmic-OS/Cosmic-OS.github.io#77]
Seamless switch to local storage needs to be reverted, it's been over a month so; if the user hasn't already opened webpage before (and has therefore been switched) their cookies have expired so it won't be seamless anyway.

**Comment by ghost** [comment]
Thanks for letting us know

**Comment by Sid-Sun** [comment]
The commit has been reverted. I had set a reminder to do so after a month but I forgot about it. Closing the issue. Thanks for your input :)
